import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "@/Components/Container";
import NavbarComponent from "@/Components/NavbarComponent";
import { AuthContextProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <NavbarComponent />
        <main className="flex-1 flex">
          <Container>
            {/* <div className="bg-black w-full flex flex-col flex-1 px-4 sm:px-6 lg:px-8"> */}
            <AuthContextProvider>{children}</AuthContextProvider>
            {/* </div> */}
          </Container>
        </main>
      </body>
    </html>
  );
}
